

INSERT INTO SERVICE_DETAIL VALUES('S1', 4.0, 'DEVICE COST', 'FOR_ALL');
INSERT INTO SERVICE_DETAIL VALUES('S2', 5.0, 'ANTIVIRUS', 'WINDOWS');
INSERT INTO SERVICE_DETAIL VALUES('S3', 7.0, 'ANTIVIRUS', 'MAC');
INSERT INTO SERVICE_DETAIL VALUES('S4', 3.0, 'BACKUP', 'FOR_ALL');
INSERT INTO SERVICE_DETAIL VALUES('S5', 2.0, 'PSA', 'FOR_ALL');
INSERT INTO SERVICE_DETAIL VALUES('S6', 1.0, 'SCREEN SHARE', 'FOR_ALL');

INSERT INTO DEVICE VALUES('D1', 'WINDOWS', 'WINDOWS WORKSTATION');
INSERT INTO DEVICE VALUES('D2', 'WINDOWS', 'WINDOWS HOME');
INSERT INTO DEVICE VALUES('D3', 'MAC', 'macOS 12 Monterey');
INSERT INTO DEVICE VALUES('D4', 'MAC', 'macOS 11');
INSERT INTO DEVICE VALUES('D5', 'MAC', 'macOS 10');


INSERT INTO DEVICES_BY_SERVICE VALUES('D1', 'S1');
INSERT INTO DEVICES_BY_SERVICE VALUES('D1', 'S2');
INSERT INTO DEVICES_BY_SERVICE VALUES('D1', 'S4');
INSERT INTO DEVICES_BY_SERVICE VALUES('D1', 'S6');

INSERT INTO DEVICES_BY_SERVICE VALUES('D2', 'S1');
INSERT INTO DEVICES_BY_SERVICE VALUES('D2', 'S2');
INSERT INTO DEVICES_BY_SERVICE VALUES('D2', 'S4');
INSERT INTO DEVICES_BY_SERVICE VALUES('D2', 'S6');

INSERT INTO DEVICES_BY_SERVICE VALUES('D3', 'S1');
INSERT INTO DEVICES_BY_SERVICE VALUES('D3', 'S3');
INSERT INTO DEVICES_BY_SERVICE VALUES('D3', 'S4');
INSERT INTO DEVICES_BY_SERVICE VALUES('D3', 'S6');

INSERT INTO DEVICES_BY_SERVICE VALUES('D4', 'S1');
INSERT INTO DEVICES_BY_SERVICE VALUES('D4', 'S3');
INSERT INTO DEVICES_BY_SERVICE VALUES('D4', 'S4');
INSERT INTO DEVICES_BY_SERVICE VALUES('D4', 'S6');

INSERT INTO DEVICES_BY_SERVICE VALUES('D5', 'S1');
INSERT INTO DEVICES_BY_SERVICE VALUES('D5', 'S3');
INSERT INTO DEVICES_BY_SERVICE VALUES('D5', 'S4');
INSERT INTO DEVICES_BY_SERVICE VALUES('D5', 'S6');